### ISSUE TITLE
Error 500 on sorting by duration time on admin panel (again)

### ISSUE THREAD

**Issue by romanandrei** [Tivix/django-cron#155] opened 2019-12-05 06:46 UTC
On django-cron==0.5.1 the following error is raised when sorting in admin by duration.
Also, I found that this problem has been raised in the past ([https://github.com/Tivix/django-cron/issues/86](url))
I checked the code in the package and the change [(https://github.com/Tivix/django-cron/commit/290e4177340e9c3093ff117fe7ed83edf39a8e08)](url) is not found.

**Comment by rpkilby** [comment] 2020-05-14 23:58
Hi @romanandrei. #93 wasn't merged, so that commit is not present in the git history. 

Closing as a duplicate of #86

**Closed by rpkilby** 2020-05-14 23:58 UTC
