### ISSUE TITLE
Multiple cron job not executed

### ISSUE THREAD

**Issue by inspiralpatterns** [Tivix/django-cron#118] opened 2017-07-28 08:13 UTC
I have several cron jobs inside the `CRON_CLASSES`. 
Inspecting the Django administrations, It seems that some of them are failing all the time, while others are not even run. 
Is there any correlation between the failing and the not-executed ones? (e.g. they are not executed because django-cron is running the ones that have failed). 

Thanks for the help, it's driving me crazy.

**Comment by jacksonofalltrades** [comment] 2018-07-03 22:22
I am also having this problem. A few of my cron classes are simply never run. I cannot figure out why.

**Comment by cptx032** [comment] 2018-11-03 13:45
Im having this problem too. Investigating I found that tasks scheduled to '23:59', maybe, doesn't run after 00:00 because django_cron only verifies hours and not dates. So if you set your job to 23:59 but the script only runs in 00:00 it will not be executed (I dont tested this). This was not my problem here, but I'm posting this here as "preliminar analisys"

**Comment by JedrzejMaluszczak** [comment] 2022-05-31 14:01
Closing because I can't reproduce that bug

**Closed by JedrzejMaluszczak** 2022-05-31 14:01 UTC
