### ISSUE TITLE
Model class django_cron.models.CronJobLog doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS

### ISSUE THREAD

**Issue by zoufou** [Tivix/django-cron#62] opened 2015-07-05 12:51 UTC
I get the below error when executing **python manage.py runcrons**

    ... venv/local/lib/python2.7/site-packages/django_cron/models.py:4: 
    RemovedInDjango19Warning: Model class django_cron.models.CronJobLog 
    doesn't declare an explicit app_label and either isn't in an application in 
    INSTALLED_APPS or else was imported before its application was loaded. This 
    will no longer be supported in Django 1.9.

**Comment by chachra** [comment] 2015-07-16 05:40
Its more of a warning, should be looked into for future Django compat.

**Comment by angvp** [comment] 2015-07-23 17:34
duplicate of #59 (fixed)

**Comment by mjaworski** [comment] 2015-09-08 12:19
Duplicate as stated.

**Closed by mjaworski** 2015-09-08 12:19 UTC
